POST http://localhost:3001/api/notes/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvbDEyNSIsImlkIjoiNjNhYjRiODAxNDlkN2E2NWJhNmUzYjY1IiwiaWF0IjoxNjcyMjIyMjQ0fQ.ZNzqMfguFJZqUtHU_esuTY55chFvIyKFhqi32g336mE

{
    "content": "Learning authentication and authorization",
    "important": true,
    "userId": "63ab4b80149d7a65ba6e3b65"
}