POST http://localhost:3001/api/notes/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbWkxMjMiLCJpZCI6IjYzYmE5NTZkYTEwODU3NTlhZmY0MjNlMSIsImlhdCI6MTY3MzE3MjM1OCwiZXhwIjoxNjczMTc1OTU4fQ.Q2q1Y1DWO6viE3GbtZWEAW6lu25IhusTE9f6R31nY-M

{
    "content": "React authentication and authorization",
    "important": true,
    "userId": "63ba956da1085759aff423e1"
}